### ISSUE TITLE
Has a lodash dependency, but that isn't in package.json

### ISSUE THREAD

**Issue by SimplGy** [LucianoGanga/simple-headless-chrome#1]
If you pull the project fresh it complains it's missing `lodash`. That dependency is not in package.json. `yarn add lodash` fixes the problem.

**Comment by LucianoGanga** [comment]
Thanks! Fixed :) 

If you find more problems let me know, and you can also submit a PR. 

Cheers!

**Comment by SimplGy** [comment]
:)
