### ISSUE TITLE
Usage example on Heroku

### ISSUE THREAD

**Issue by stpe** [LucianoGanga/simple-headless-chrome#13]
Would be great with a documented example of how to get this to work on Heroku.

Using it locally is not a problem, but with the buildpack deploy on Heroku I always get `ECONNREFUSED`. I assume it has something to do with processes being assigned random port numbers?

```
{ Error: connect ECONNREFUSED 127.0.0.1:47063
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 47063 }```

**Comment by LucianoGanga** [comment]
I'm having the same issue. It seems to be a limitation of the dyno. 

What Heroku plan are you using?

**Comment by stpe** [comment]
So far I've just experimented on a Hobby plan.

I've come across the following which seems related: https://stackoverflow.com/questions/43218262/heroku-headless-chrome-connection-refused

**Comment by LucianoGanga** [comment]
I'm experimenting the same sue but after a few runs of different chrome instances. Did you find something else? 
I'm running out of ideas here :(

**Comment by LucianoGanga** [comment]
Closing this, as it seems to be a Dyno limitation problem.
