### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by Avaray** [LucianoGanga/simple-headless-chrome#2]
Are you planning to add Windows support?

From what I understand there is no difference in "how it works" between Linux and Windows versions of Chrome. The only difference is that binary file is named chrome.exe in Windows and google-chrome in Linux. Am I right?

**Comment by LucianoGanga** [comment]
I can't test it on Windows, but for what I know so far, you're right. Just give it a try! 

This module uses lighthouse's chromeLauncher, and it makes use of this file: 

https://github.com/GoogleChrome/lighthouse/blob/v2.0.0/chrome-launcher/chrome-finder.ts

So, I think it should just work if your Chrome version is 59+

Please let me know if you could make it work, or if you need some help, so other people can benefit from your doubt :) 

Cheers!
Luciano

**Comment by Avaray** [comment]
Yes, You are right. 

In Readme file you only mentioned about Mac and Linux.
So... Error that I got yesterday misleaded me to think there is no support for Windows.

Anyway - It's something with "await". I can't use `await`.  
Example error:  
`await browser.goTo('https://github.com/')
      ^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3`

I have this error in NodeJS 8.0.0 and 7.10.0 (I didn't test in older versions).

Actions without "await" works fine when I use them in Node console.

**Comment by LucianoGanga** [comment]
That's weird. I'm running all this in Node 7.10.0, and I don't have that problem. 

Where are you calling that fn? It needs to be inside an async fn. Something like this (assuming you've already initialized the browser): 
```js
async function navigateGoogle () {
    await browser.goTo('www.google.com')
}
```

**Comment by Avaray** [comment]
Ohhh...... this explains everything.  
Sorry for your trouble.
