### ISSUE TITLE
Script not terminating after execution.

### ISSUE THREAD

**Issue by mlessio** [LucianoGanga/simple-headless-chrome#20]
Scripts are waiting some time before exiting after the execution.
The script is waiting for the timeout to resolve, after the default sleep timeout (60000ms), then it returns to the console.

It seems a problem related to the setTimeout in the promiseTimeout method.

Just opened a PR that fixes this issue here: #19

**Comment by LucianoGanga** [comment]
Done! Merged and published @2.5.10. 

Thanks for your improvement @mlessio ! :D

**Comment by mlessio** [comment]
Great! Blazing fast! :D
