### ISSUE TITLE
How to click on elements if there is no class or id 

### ISSUE THREAD

**Issue by anuragvijayvergia** [LucianoGanga/simple-headless-chrome#21]
Hi ,

I am exploring this module , and I want to move my code from node horseman to this library. But I have few elements which neither have an id no a class , is it possible to do something like this 
.click('a[href="xyz.aspx"]')

e.g. element :  <a href="xzy.aspx" class="">xyzzy</a>

Thanks

**Comment by cazinge** [comment]
Hi @anuragvijayvergia, your first instinct about your selector was correct, 'a[href="xyz.aspx"]' would select the element with an href value pointing towards that URL [source](https://css-tricks.com/almanac/selectors/a/attribute/).

The function you used to call it however, `.click()` is invalid syntax with simple-headless-chrome. Unlike horseman, simple-headless-chrome requires you to invoke `browser` as an asynchronous request any time you wish to perform an action on it. 

Your code would likely end up looking something like `await browser.click('a[href="xyz.aspx"]')`, inside of an async function.

**Comment by LucianoGanga** [comment]
@cazinge thanks for helping answering this question! 👍 

@anuragvijayvergia , I hope that @cazinge answer helped you. Let us know if your problem persists. 

Thanks!
Lucho
