### ISSUE TITLE
network monitoring?

### ISSUE THREAD

**Issue by aphid** [LucianoGanga/simple-headless-chrome#23]
This is working great so far.  I was wondering if there's a way to do network monitoring, similar to http://phantomjs.org/api/webpage/handler/on-resource-requested.html

**Comment by LucianoGanga** [comment]
Hi @aphid ! Sorry for the late reply. 

Yes, you can implement an event from this Domain:
https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent

I'm not able to do it now, but if you need it with some rush, you can fork this module and add the method to do that; check out this file to see how to do it: 
https://github.com/LucianoGanga/simple-headless-chrome/blob/master/lib/setupHandlers.js

If you need some help with this, just tell me :) 

Cheers!
Luciano

**Comment by LucianoGanga** [comment]
Hello @aphid ! I wanted to know if that was useful for you, or if you still have the problem. 

Thanks!
Lucho

**Comment by LucianoGanga** [comment]
@aphid I added the full set of network events in the module. 

You can check the example here: 
https://github.com/LucianoGanga/simple-headless-chrome/blob/master/examples/networkMonitoring.js

And you can see all the events here: 
https://chromedevtools.github.io/devtools-protocol/tot/Network/ (all those under the "Events" title) 

If this doesn't answer your doubts, please fell free to reopen the issue.

Cheers!
Lucho

**Comment by aphid** [comment]
Wonderful, thanks!
