### ISSUE TITLE
Make `simple-headless-chrome` run in node LTS

### ISSUE THREAD

**Issue by gr2m** [LucianoGanga/simple-headless-chrome#31]
hey @LucianoGanga I wonder if you would be okay to change the code of the `lib/*` files so that the library would run in older node versions? We can still use async/await in tests. And I don’t think that the code become less readable. 

We have a project where we would love to use `simple-headless-chrome` but can’t right now because we can’t upgrade the node versions anytime soon :( I’d be happy to send a PR myself. If you are unsure, I can start so you can see some of the diff. Let me know :)

**Comment by nicolaivadim** [comment]
Using babel on server-side is not an option ?

**Comment by gr2m** [comment]
Not in this case. For libraries, I’d say it’s good practise to not require build tools to run in Node LTS version. Your apps still can use `async`/`await`, it would make no difference, it’s just an internal implementation detail

**Comment by LucianoGanga** [comment]
Hello @gr2m ! The true is that I never thought of that before. I wrote it using async / await to avoid callbacks, and to make it clearer for me. 

I'm merging a PR by @lewisf now, who made a really nice contribution to allow Node >= 4 use this module :) 

I'll let you know as soon as it's published! 

Lucho

**Comment by LucianoGanga** [comment]
@gr2m , the package is ready under version 3.0.1 :) 

Let me know if something doesn't work. 

Cheers!
Lucho

**Comment by LucianoGanga** [comment]
Quick update. I just added another PR, so the last published version is 3.1.0.

Lucho

**Comment by gr2m** [comment]
Thanks a lot, I’ll give this a try the coming week!
