### ISSUE TITLE
Simple working example?

### ISSUE THREAD

**Issue by prajeeshkayyur** [LucianoGanga/simple-headless-chrome#33]
const HeadlessChrome = require('simple-headless-chrome')

const browser = new HeadlessChrome({
  headless: true // If you turn this off, you can actually see the browser navigate with your instructions,
  chrome: {
    userDataDir: '/tmp/headlessDataDir' // This can be null, so a tmp folder will be created and then destroyed
  }
})

browser.goTo("http://www.google.com");

(node:31486) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: browser.goTo is not a function

Throws error and it is not working as expected or  am I missing something? 

As per the documentation this module compatible for node>=4., could you please share a simple working example in node 6.x, I mean without using async and await. 

This will be very helpful for beginners like me.....

**Comment by gr2m** [comment]
@prajeeshkayyur I have a minimal test setup here: https://github.com/gr2m/headless-chrome-test

I think you have to wait for ` await browser.init()` to resolve before using any other methods.

Try this

```js
const HeadlessChrome = require('simple-headless-chrome')

const browser = new HeadlessChrome({
  headless: true
  chrome: { userDataDir: '/tmp/headlessDataDir' }
})

browser.init()
  .then(() => {
    return browser.goTo("http://www.google.com")
  })
  .catch(console.log)
```

**Comment by prajeeshkayyur** [comment]
Thank you!. But still I'm getting error.

      `  const browser = new HeadlessChrome({
            headless: true,
            launchChrome: true ,
            chrome: {
                host: 'localhost',
                port: 9222, // Chrome Docker default port
                remote: true,
            },
            browserlog: true
        });

        this.browser = browser.init().then(function (data) {

            return browser;

        }, function (err) {
            console.log(err)
        })

        console.log(this.browser.goTo); // getting as undefined`

**Comment by prajeeshkayyur** [comment]
One more question, how to use getValue?
`
let value = this.browser.getValue(context).then(function(value) {
            console.log("hello"); // not printing this or anything
            if(value){
                console.log(value);
                return value;
            }
        }).catch(function (err) {
            if(err){
                console.log("Error fetching element", err); /// no error too...
            }
        });
console.log(value); /// shows promises
 `

**Comment by LucianoGanga** [comment]
Hi @prajeeshkayyur ! 

You can't get the value like that. When the promise resolves, you get the value inside the promise but can't get it outside in the same line. 

You can read a little bit more here: https://stackoverflow.com/a/29516570/3078968

I hope it helps!

Cheers!
Lucho

**Comment by prajeeshkayyur** [comment]
after wrapping the response with promise, It worked for me. Actually I was integrating headless chrome driver to codeceptJS with the help of simple-headless-chrome. It worked nicely!!!

**Comment by LucianoGanga** [comment]
I'm glad it was useful to you @prajeeshkayyur !  
If you think that what you did may be useful for somebody else, feel free to upload it as an example inside the "/examples" directory :) 

Thanks!
Lucho
