### ISSUE TITLE
On inject, evaluate script directly

### ISSUE THREAD

**Issue by vadimnicolai** [LucianoGanga/simple-headless-chrome#35]
I've tried to evaluate with script.textContent, but no success.
What would you recommend instead ?

**Comment by LucianoGanga** [comment]
Can you write an example of what you've tried? 

Thanks!
Lucho

**Comment by LucianoGanga** [comment]
Hi @vadimnicolai ! 

Could you solve the issue? 

Cheers!
Lucho

**Comment by LucianoGanga** [comment]
Closed due to lack of activity. If you didn't solved it, please feel free to reopen it :) 

Thanks!
Lucho
