### ISSUE TITLE
Looks great, but possible to use with only remote debugging?

### ISSUE THREAD

**Issue by bobbysteel** [LucianoGanga/simple-headless-chrome#4]
Looks like this really solves my problem, but I'm using Chrome headless in a docker image, so I only want to interface w/ port 9222. This seems to use the binaries and maybe phantomjs in the npm install?

**Comment by LucianoGanga** [comment]
Hi! Could you solve it? 

There's a way to use it remotely. I couldn't document it yet, but if you send the host, port and a variable indicating that you're debugging remotely, that's it. Oh, and you also must indicate the module don't to launch Chrome. 

So, your settings object will look something like: 

```js 
const settings = {
    launchChrome: false,
    chrome: {
        host: 'http://yourhost.com',
        port: 9222,
        remote: true
    }
}
```

I hope it helps. 

Please, if you make it work, and you can submit a PR with an example in the readme, that will be awesome! So others can benefit from this too. 

Thanks!
Luciano

**Comment by bobbysteel** [comment]
Yep will document this as soon as I get my first end-to-end test working :)
