### ISSUE TITLE
browser.click doesn't handle long selectors

### ISSUE THREAD

**Issue by fusionx1** [LucianoGanga/simple-headless-chrome#44]
1. Im getting an error if I put a string like this as my selector:
await browser.click('a[href="/accounts/1388696/applications/20920975"]')
I get this: 
(node:13030) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Can not query selector a[href='/accounts/'1388696/applications/20920975'] in frame "root": Error: DOM Error while querying

2. Im getting an error if I put a string like this as my selector:
await browser.click('div ul\:nth-child(3) li.app-box.editable div.single-portal-app')
I get this:
(node:76434) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Can not query selector div ul\:nth-child(3) li.app-box.editable div.single-portal-app in frame "root": Error: DOM Error while querying
(node:76434) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fusionx1** [comment]
Would be great if can be able to handle xpath

**Comment by LucianoGanga** [comment]
Could you solve this? 
There's no limitation for selectors. 

Can you send a PR with a test with this scenario so I can test this and find a solution? 

Thanks!
Lucho

**Comment by LucianoGanga** [comment]
(To upload a test, just copy/paste the basic.js file in the tests directory. Let me know if you need some help with that :) )

**Comment by LucianoGanga** [comment]
Hello @fusionx1 ! 

I could make some time today to make a test case with this. The issue wasn't the long selector, but the :nth-child. 

I added a nice module called [`cssesc`](https://github.com/mathiasbynens/cssesc), that solves this issue and replaces the function I made before (an ugly one) to escape selectors before passing them to the browser. 

I'll be published soon in NPM, so I'll tell you here when it's ready. 

Thanks for finding the issue! And sorry for the late reply.

Luciano

PS: You can check the example code here: https://github.com/LucianoGanga/simple-headless-chrome/blob/master/examples/clickSelector.js

**Comment by LucianoGanga** [comment]
Done! 

Published as v4.1.0 :) 

I hope it helps! 

Lucho

**Comment by fusionx1** [comment]
Wow you are awesome bro. Thank you.
