### ISSUE TITLE
getValue returns undefined

### ISSUE THREAD

**Issue by bobbysteel** [LucianoGanga/simple-headless-chrome#6]
Hm. Not sure if this is my error or a bug.

Using getValue returns undefined for a valid element.

```   
  // <div class="graph-metric-current">Test</div>
    var alpha = await browser.getValue('.graph-metric-current')
    console.log(alpha)
```
The returned should be a HTML value of the .graph-metric-current node shouldn't it? Using util.inspect also returns undefined, so I'm not quite sure what the object is meant to be.

Cheers

**Comment by bobbysteel** [comment]
I'm trying this with evaluate now which I suspect may be a better solution but getting a syntax error:
```   var test = await browser.evaluate({
    'expression': 'window.location.toString()'
});
```
returns a syntax error. Looking at the remote interface that seems to be valid syntax?

**Comment by bobbysteel** [comment]
Ah, seems that requires a function input. Not sure how to extract data better, but creating a evaluateElement function removing the .apply gives the desired result. Would it make sense to add a function to evaluate simple non-function expressions? This would allow for extracting page elements more easily.

**Comment by LucianoGanga** [comment]
Hi @bobbysteel ! 

Regarding the first comment, I didn't code the .getValue() method thinking on how to get the text between HTML tags; it was made to get HTML Form elements values. I think that for that case, it's better to get it using .evaluate(), which refers also to your second message: 

The correct way to use the .evaluate method is this: 

```js
const location = await browser.evaluate(function(selector) {
    const selectorHtml = document.querySelector('.graph-metric-current') 
    return selectorHtml.innerText
}, selector);
``` 


About the debugging, you just need to start the app setting an environment variable called DEBUG, to the value "HeadlessChrome:[file]', like this:

```
DEBUG='HeadlessChrome:actions' npm start
```

or:
```
DEBUG='HeadlessChrome:browser' npm start
```
or, if you want all the logs:
```
DEBUG='HeadlessChrome:*' npm start
```

I hope it helps! 
Luciano

**Comment by bobbysteel** [comment]
Thanks Luciano. I'm almost there, but in your sample it throws ReferenceError: selector is not defined. I'm probably being really dumb here but what am I missing?

**Comment by LucianoGanga** [comment]
My example was wrong! haha, sorry! 
I just corrected it, can you check it? Tell me if it doesn't work :)

**Comment by bobbysteel** [comment]
MAGIC! Thanks!!!
