### ISSUE TITLE
We need to run browser with proxy,How i set proxy?

### ISSUE THREAD

**Issue by iyyappan13391** [LucianoGanga/simple-headless-chrome#66]
we are using NPM of simple-headless-chorme. I have tried to set proxy of it.Even this cannot having the correct document to the proxy.Can you help me to get this things done?

**Comment by LucianoGanga** [comment]
Hello @iyyappan13391 ! 

I don't understand what you need to do. You need to add a proxy to the navigation? 

I think that's something you can do at a network level, and not from the Headless Chrome. 

Thanks!
Lucho

**Comment by timo-klarshift** [comment]
Just start your chrome with: chromium --headless --proxy-server=host:port [...]

**Comment by LucianoGanga** [comment]
In that case, if it's with a flag, you can pass flags when initializing the instance. Check the example here: 

https://github.com/LucianoGanga/simple-headless-chrome#support-more-chrome-flags

Cheers!
Luciano
