### ISSUE TITLE
Function "visible" missing await

### ISSUE THREAD

**Issue by mdickin** [LucianoGanga/simple-headless-chrome#69]
When I try to call `visible`, I get the following error:

"TypeError: Cannot read property 'value' of undefined"

Looking at the source, every other call to `this.evaluate()` uses `await`, but `visible` handles it synchronously.

When I moved `visible.result.value` to a `.then()` handler, it worked fine.

**Comment by LucianoGanga** [comment]
Thanks @mdickin !! 
I fixed it in v4.3.10 :) 

Cheers!
Luciano
