### ISSUE TITLE
(node:36029) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by Tin-Nguyen** [LucianoGanga/simple-headless-chrome#72]
Hi all,

I got the issue every time with high-load print to PDF using `simple-headless-chrome`.

```
(node:36029) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
```

Please check if it's an issue of the lib

**Comment by LucianoGanga** [comment]
Hi! 

That happened to me when running many instances in the same machine. I fix it by distributing the time between the launch of new chrome instances. 

I know it's not the "final" solution, but maybe it gives you some idea about what's generating that on your computer.

Cheers!
Lucho

**Comment by Tin-Nguyen** [comment]
Hi @LucianoGanga , thanks for your working on this issue.  I will try to upgrade the latest version of `simple-headless-chrome` and check the issue.

However, I'm wondering your found issue is the same as my issue or not, since I'm using an existing Chrome instance in Docker and remotely connect my service to it. Thoughts?
