### ISSUE TITLE
Puppeteer?

### ISSUE THREAD

**Issue by tommedema** [LucianoGanga/simple-headless-chrome#74]
Just curious, was this library initiated before or after [puppeteer](https://github.com/GoogleChrome/puppeteer)?

Do you see the two libraries living alongside each other or do they serve the same purpose?

**Comment by LucianoGanga** [comment]
Hi! 
To be honest, I don't know. I heard of puppeteer about a month ago but I started this on May. 

I think you shouldn't have any problem with both libraries living alongside, but they do the same thing. 

Which you may use depends on which of them you like more (maybe the syntax or the abstracted methods) .

Cheers!
Lucho
