### ISSUE TITLE
[Question] Can I load a local html file and transform it into PDF ?

### ISSUE THREAD

**Issue by rlataguerra** [LucianoGanga/simple-headless-chrome#83]
Hi,
I dont see anything in the documentation about opening a local file.
Is that possible ?

**Comment by LucianoGanga** [comment]
Hi!

As long as you can pass the local HTML URL, you will be ok. Try first opening that html in Chrome, just by dragging the file into the browser.. then copy that URL and try navigating through the headless chrome .

Cheers!
Luciano
